params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [512, 512, 256, 128]
      # units:  [256, 256, 128, 128]
      activation: elu
      d2rl: False
      initializer:
        name: default
      regularizer:
        name: None

    # rnn:
    #   name: lstm
    #   units: 256
    #   layers: 1
    #   before_mlp: False
    #   concat_input: True
    #   layer_norm: True

  config:
    name: smg_reorient
    full_experiment_name: ${.name}
    env_name: rlgpu
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.num_envs}
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    lr_schedule: adaptive
    schedule_type: standard
    kl_threshold: 0.016
    score_to_win: 100000
    max_epochs: ${resolve_default:400,${....max_iterations}}
    use_diagnostics: True
    save_best_after: 100
    save_frequency: 250
    entropy_coef: 0.0
    truncate_grads: True
    grad_norm: 1.0
    e_clip: 0.2

    # horizon_length: 1024
    # minibatch_size: 256

    # horizon_length: 8
    # minibatch_size: 16384

    horizon_length: 32
    minibatch_size: 32768

    mini_epochs: 5
    critic_coef: 4
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001

    # use_experimental_cv: true
    # central_value_config:
    #   minibatch_size: ${..num_actors}
    #   mini_epochs: ${..mini_epochs}
    #   learning_rate: 0.0005
    #   lr_schedule: adaptive
    #   schedule_type: standard
    #   kl_threshold: 0.016
    #   clip_value: true
    #   normalize_input: true
    #   truncate_grads: true
    #   network:
    #     name: actor_critic
    #     central_value: true
    #     mlp:
    #       units: [512, 512, 256, 128]
    #       activation: elu
    #       d2rl: false
    #       initializer:
    #         name: default
    #       regularizer:
    #         name: None


    print_stats: False
    progress_bar: True

    player:
      #render: True
      deterministic: True
      games_num: 100000
      print_stats: False
